/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ViewSlugRouteImport } from './routes/view/$slug'
import { Route as AdminViewRouteImport } from './routes/admin/view'
import { Route as AdminCreateRouteImport } from './routes/admin/create'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminEditSlugRouteImport } from './routes/admin/edit/$slug'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ViewSlugRoute = ViewSlugRouteImport.update({
  id: '/view/$slug',
  path: '/view/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminViewRoute = AdminViewRouteImport.update({
  id: '/view',
  path: '/view',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCreateRoute = AdminCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEditSlugRoute = AdminEditSlugRouteImport.update({
  id: '/edit/$slug',
  path: '/edit/$slug',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/admin/create': typeof AdminCreateRoute
  '/admin/view': typeof AdminViewRoute
  '/view/$slug': typeof ViewSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/edit/$slug': typeof AdminEditSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/admin/create': typeof AdminCreateRoute
  '/admin/view': typeof AdminViewRoute
  '/view/$slug': typeof ViewSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/edit/$slug': typeof AdminEditSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/admin/create': typeof AdminCreateRoute
  '/admin/view': typeof AdminViewRoute
  '/view/$slug': typeof ViewSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/edit/$slug': typeof AdminEditSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/projects'
    | '/admin/create'
    | '/admin/view'
    | '/view/$slug'
    | '/admin/'
    | '/admin/edit/$slug'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects'
    | '/admin/create'
    | '/admin/view'
    | '/view/$slug'
    | '/admin'
    | '/admin/edit/$slug'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/projects'
    | '/admin/create'
    | '/admin/view'
    | '/view/$slug'
    | '/admin/'
    | '/admin/edit/$slug'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ProjectsRoute: typeof ProjectsRoute
  ViewSlugRoute: typeof ViewSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/view/$slug': {
      id: '/view/$slug'
      path: '/view/$slug'
      fullPath: '/view/$slug'
      preLoaderRoute: typeof ViewSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/view': {
      id: '/admin/view'
      path: '/view'
      fullPath: '/admin/view'
      preLoaderRoute: typeof AdminViewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/create': {
      id: '/admin/create'
      path: '/create'
      fullPath: '/admin/create'
      preLoaderRoute: typeof AdminCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/edit/$slug': {
      id: '/admin/edit/$slug'
      path: '/edit/$slug'
      fullPath: '/admin/edit/$slug'
      preLoaderRoute: typeof AdminEditSlugRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminCreateRoute: typeof AdminCreateRoute
  AdminViewRoute: typeof AdminViewRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEditSlugRoute: typeof AdminEditSlugRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCreateRoute: AdminCreateRoute,
  AdminViewRoute: AdminViewRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEditSlugRoute: AdminEditSlugRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ProjectsRoute: ProjectsRoute,
  ViewSlugRoute: ViewSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
